#!/bin/bash

#############################################
# XAUUSD Momentum Bot - Installer (FIXED)
# Bybit Edition - 100% Free Unlimited
#############################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

BOT_DIR="/opt/xauusd-bot"
SERVICE_NAME="xauusd-bot"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}This script must be run as root (use sudo)${NC}" 
   exit 1
fi

#############################################
# Helper Functions
#############################################

print_header() {
    clear
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}   XAUUSD Momentum Bot - Installer${NC}"
    echo -e "${BLUE}   Bybit Edition (100% Free)${NC}"
    echo -e "${BLUE}========================================${NC}"
    echo ""
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_info() {
    echo -e "${YELLOW}➜ $1${NC}"
}

#############################################
# Installation Functions
#############################################

install_dependencies() {
    print_info "Installing system dependencies..."
    
    apt-get update -qq
    apt-get install -y python3 python3-pip python3-venv curl wget > /dev/null 2>&1
    
    print_success "Dependencies installed"
}

setup_bot_directory() {
    print_info "Setting up bot directory..."
    
    # Create directories
    mkdir -p "$BOT_DIR"
    mkdir -p "$BOT_DIR/logs"
    
    # Copy files
    cp "$SCRIPT_DIR/bot.py" "$BOT_DIR/"
    cp "$SCRIPT_DIR/requirements.txt" "$BOT_DIR/"
    cp "$SCRIPT_DIR/config.py.template" "$BOT_DIR/"
    
    # Set permissions
    chmod +x "$BOT_DIR/bot.py"
    
    print_success "Bot directory created at $BOT_DIR"
}

install_python_packages() {
    print_info "Installing Python packages..."
    
    cd "$BOT_DIR"
    
    # Create virtual environment
    python3 -m venv venv
    source venv/bin/activate
    
    # Install packages
    pip install --quiet --upgrade pip
    pip install --quiet -r requirements.txt
    
    deactivate
    
    print_success "Python packages installed"
}

configure_bot() {
    print_header
    echo -e "${GREEN}Bot Configuration${NC}"
    echo ""
    
    # Get Discord webhook
    echo -e "${YELLOW}1. Discord Webhook URL${NC}"
    echo "   Get it from: Discord Channel → Settings → Integrations → Webhooks"
    echo ""
    read -p "Enter Discord Webhook URL: " webhook_url
    
    # Validate webhook
    if [[ ! $webhook_url =~ ^https://discord.com/api/webhooks/ ]]; then
        print_error "Invalid Discord webhook URL"
        exit 1
    fi
    
    echo ""
    echo -e "${YELLOW}2. Momentum Settings${NC}"
    echo "   Default: M5=40 pips, M15=50 pips (Sekolah Trading standard)"
    echo ""
    read -p "M5 minimum body (pips) [40]: " m5_pips
    m5_pips=${m5_pips:-40}
    
    read -p "M15 minimum body (pips) [50]: " m15_pips
    m15_pips=${m15_pips:-50}
    
    echo ""
    echo -e "${YELLOW}3. Wick Filter${NC}"
    read -p "Maximum wick percentage (0-100) [30]: " max_wick
    max_wick=${max_wick:-30}
    max_wick=$(echo "scale=2; $max_wick / 100" | bc)
    
    # Create config.py
    cat > "$BOT_DIR/config.py" << EOF
"""
Configuration for XAUUSD Momentum Bot
Generated by install.sh on $(date)
"""

# Discord webhook URL
DISCORD_WEBHOOK_URL = "$webhook_url"

# Momentum thresholds (in pips)
MOMENTUM_PIPS_M5 = $m5_pips   # M5 body minimum in pips
MOMENTUM_PIPS_M15 = $m15_pips  # M15 body minimum in pips

# Wick filter (max percentage)
MAX_WICK_PERCENTAGE = $max_wick  # Maximum wick percentage

# Alert settings
ALERT_COOLDOWN = 60  # Seconds between alerts for same timeframe

# Pip size for XAUUSD
PIP_SIZE_XAUUSD = 0.1  # 1 pip = 0.1 price for gold
EOF
    
    chmod 600 "$BOT_DIR/config.py"
    
    print_success "Configuration saved"
}

create_systemd_service() {
    print_info "Creating systemd service..."
    
    cat > "/etc/systemd/system/$SERVICE_NAME.service" << EOF
[Unit]
Description=XAUUSD Momentum Bot (Bybit)
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=$BOT_DIR
ExecStart=$BOT_DIR/venv/bin/python $BOT_DIR/bot.py
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF
    
    systemctl daemon-reload
    systemctl enable "$SERVICE_NAME" > /dev/null 2>&1
    
    print_success "Systemd service created"
}

test_discord() {
    print_info "Testing Discord webhook..."
    
    cd "$BOT_DIR"
    source venv/bin/activate
    
    python3 << 'EOFPYTHON'
import sys
sys.path.insert(0, '/opt/xauusd-bot')

try:
    import requests
    from config import DISCORD_WEBHOOK_URL
    
    msg = {
        "embeds": [{
            "title": "✅ Test Alert",
            "description": "XAUUSD Momentum Bot successfully installed!",
            "color": 3447003,
            "fields": [
                {"name": "Status", "value": "Ready to monitor", "inline": True},
                {"name": "Source", "value": "Bybit XAUUSDT", "inline": True}
            ]
        }]
    }
    
    r = requests.post(DISCORD_WEBHOOK_URL, json=msg, timeout=10)
    if r.status_code == 204:
        print("✓ Discord test successful")
    else:
        print(f"✗ Discord test failed: {r.status_code}")
except Exception as e:
    print(f"✗ Error: {e}")
EOFPYTHON
    
    deactivate
}

#############################################
# Management Menu
#############################################

show_status() {
    print_header
    echo -e "${GREEN}Bot Status${NC}"
    echo ""
    systemctl status "$SERVICE_NAME" --no-pager
}

show_logs() {
    print_header
    echo -e "${GREEN}Bot Logs (Ctrl+C to exit)${NC}"
    echo ""
    journalctl -u "$SERVICE_NAME" -f
}

show_stats() {
    print_header
    echo -e "${GREEN}Bot Statistics${NC}"
    echo ""
    
    if [ -f "$BOT_DIR/logs/bot.log" ]; then
        echo "Recent alerts:"
        grep "Discord alert sent" "$BOT_DIR/logs/bot.log" | tail -10
    else
        echo "No statistics available yet"
    fi
}

edit_config() {
    nano "$BOT_DIR/config.py"
    systemctl restart "$SERVICE_NAME"
    print_success "Configuration updated and bot restarted"
}

uninstall_bot() {
    print_header
    echo -e "${RED}⚠️  UNINSTALL BOT${NC}"
    echo ""
    echo "This will remove:"
    echo "  - Bot files ($BOT_DIR)"
    echo "  - Systemd service"
    echo "  - All logs"
    echo ""
    read -p "Type 'UNINSTALL' to confirm: " confirm
    
    if [ "$confirm" != "UNINSTALL" ]; then
        print_error "Uninstall cancelled"
        return
    fi
    
    systemctl stop "$SERVICE_NAME" 2>/dev/null || true
    systemctl disable "$SERVICE_NAME" 2>/dev/null || true
    rm -f "/etc/systemd/system/$SERVICE_NAME.service"
    systemctl daemon-reload
    rm -rf "$BOT_DIR"
    
    print_success "Bot uninstalled successfully"
    exit 0
}

management_menu() {
    while true; do
        print_header
        echo -e "${GREEN}Management Menu${NC}"
        echo ""
        echo "1) Start Bot"
        echo "2) Stop Bot"
        echo "3) Restart Bot"
        echo "4) View Status"
        echo "5) View Logs (live)"
        echo "6) View Statistics"
        echo "7) Edit Configuration"
        echo "8) Test Discord Alert"
        echo "9) Uninstall Bot"
        echo "0) Exit"
        echo ""
        read -p "Select option: " choice
        
        case $choice in
            1)
                systemctl start "$SERVICE_NAME"
                print_success "Bot started"
                sleep 2
                ;;
            2)
                systemctl stop "$SERVICE_NAME"
                print_success "Bot stopped"
                sleep 2
                ;;
            3)
                systemctl restart "$SERVICE_NAME"
                print_success "Bot restarted"
                sleep 2
                ;;
            4)
                show_status
                read -p "Press Enter to continue..."
                ;;
            5)
                show_logs
                ;;
            6)
                show_stats
                read -p "Press Enter to continue..."
                ;;
            7)
                edit_config
                ;;
            8)
                test_discord
                read -p "Press Enter to continue..."
                ;;
            9)
                uninstall_bot
                ;;
            0)
                exit 0
                ;;
            *)
                print_error "Invalid option"
                sleep 1
                ;;
        esac
    done
}

#############################################
# Main Installation
#############################################

main_install() {
    print_header
    
    echo -e "${GREEN}Starting installation...${NC}"
    echo ""
    
    install_dependencies
    setup_bot_directory
    install_python_packages
    configure_bot
    create_systemd_service
    
    echo ""
    print_success "Installation complete!"
    echo ""
    
    # Test Discord
    echo -e "${YELLOW}Testing Discord connection...${NC}"
    test_discord
    echo ""
    
    # Start bot
    read -p "Start bot now? (y/n): " start_now
    if [ "$start_now" = "y" ] || [ "$start_now" = "Y" ]; then
        systemctl start "$SERVICE_NAME"
        print_success "Bot started!"
    fi
    
    echo ""
    echo -e "${GREEN}========================================${NC}"
    echo -e "${GREEN}Installation Summary:${NC}"
    echo -e "${GREEN}========================================${NC}"
    echo ""
    echo "Bot Location: $BOT_DIR"
    echo "Service: $SERVICE_NAME"
    echo "Logs: journalctl -u $SERVICE_NAME -f"
    echo ""
    echo "Quick Commands:"
    echo "  sudo systemctl start $SERVICE_NAME"
    echo "  sudo systemctl stop $SERVICE_NAME"
    echo "  sudo systemctl restart $SERVICE_NAME"
    echo "  sudo systemctl status $SERVICE_NAME"
    echo ""
    echo "Run this script again for management menu"
    echo ""
}

#############################################
# Entry Point
#############################################

# Check if bot is already installed
if [ -f "/etc/systemd/system/$SERVICE_NAME.service" ]; then
    # Show management menu
    management_menu
else
    # Run installation
    main_install
fi
